#file: noinspection SpellCheckingInspection
# For more information: https://laravel.com/docs/sail
services:
  fp:
    image: myapp/frankenphp-test
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      # laravel
      - '9999:9999'
    environment:
      PORT: 9999
    #user: '33:33'
    networks:
      - fp-network
networks:
  fp-network:
    driver: bridge
